version: '3.9'
services:
  app:
    build: .
    container_name: php
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - app-group
  
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_DATABASE:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-group

volumes:
  pg_data:

networks:
  app-group:
    name: app-group
    driver: bridge
